server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: wallet-service
              uri: lb://WALLET-SERVICE
              predicates:
                - Path=/wallet/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret-key: 1234567890123456789012345678901234567890123456789012345678901234